### PR TITLE
Attempt to show flow sizes

### PR DESCRIPTION
**Pull request by toobaz**
Example:

```
data = pd.DataFrame([[1, 'a', 1, 'I', 1, 'success'],
                     [2, 'b', 2, 'III', 2, 'discard'],
                     [1, 'b', 1, 'II', 2, 'success'],
                     [1, 'c', 1, 'II', 2, 'discard'],
                     [2.5, 'a', 2, 'IV', 1, 'discard'],
                     [2, 'a', 1, 'I', 1, 'success']],
                    columns=['Weight', 'First', 'Then', 'After', 'Finally', 'Outcome'])


plt.figure(figsize=(12, 3))
sankey(data, flow_sizes_format=' ({})')
```

download

Comments?

### CODE REVIEW

**Comment by sandrotosi** [comment]
This seems more or less what i'm looking for; the only thing that looks _out of place_ is the location of the flow size.

I did a quick search on google images, and it looks like there are mostly 2 types of organization of labels and values (this is for generic diagrams, there are a lot of fancy images, but those are just for specific instances, that dont apply for the generic case this library try to solve):

1. only 2 or 3 columns are displayed (source / destination), and if that's the case, usually label and value are on the same line:






2. several columns are displayed, and in this case they display the label and the value on 2 separate lines







Does `flow_sizes_format` support both? in that case, it would be useful to prepare 2 example for both representations. Otherwise it looks like option 2 (value below label) is the more generic?

**Comment by toobaz** [comment]
> Does `flow_sizes_format` support both?

Yes, if we use
```
sankey(data, flow_sizes_format=' \n{}')
```
we get indeed
download

The result is not optimal because of the font size, which is however a problem to be handled regardless of this PR.

I'm still not 100% satisfied about this solution... maybe I could allow also "True" as a value for the ``flow_sizes_format`` (or just ``flow_sizes``) argument, which would be equivalent to ``' ({})'``.

**Comment by toobaz** [comment]
Also:
```python3
sankey(data, flow_sizes_format=' \n\${:.2f} billion')
```

download (1)

**Comment by toobaz** [comment]
~~Not sure why it's not showing in this page, but I pushed two more commits to the branch:
https://github.com/toobaz/mpl_sankey/commits/flow_sizes~~

The syntax is now a bit better, as reflected in [the examples](https://github.com/toobaz/mpl_sankey/blob/238d72f938fa8a4798e752532ee172b6d3030b02/notebooks/Examples.ipynb) (bottom section). I'm still not 100% sure about what would be the most sane default for ``True``, but if @sandrotosi you don't have a strong opinion I guess I'll merge as it is.

**Comment by sandrotosi** [comment]
I kinda agree that the font size should be handled, maybe just set it 2-4 points smaller than the main label (if `node_sizes` is set)?

**Comment by toobaz** [comment]
OK, in the end allowing the user to decide the font size was so simple that I just added it in this PR.

**Comment by sandrotosi** [comment]
i'm afraid the main message of my last comment was lost: i was suggesting to change the font of the `node_sizes` text only, or at least change it separately from the main label.

the new `labels_size` argument changes the font for both the label and the size

**Comment by sandrotosi** [comment]
it addition it looks like the node size calculation for stages after the first is wrong:

Figure_2

column `Then`, block `2` it cant possibly be just $3b, since it's receiving $2b from `b` plus $2.5b from `a`, so that's something that needs fixing i guess

**Comment by toobaz** [comment]
> the new `labels_size` argument changes the font for both the label and the size

Yes, you're right. I'm not against allowing different sizes, but I couldn't find a nice way to do it. If you have some API in mind would you mind opening a new issue?

**Pull request merged**
